language: android

sudo: false

cache:
  directories:
    - $HOME/.gradle

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-24
    - sys-img-armeabi-v7a-android-21
    - extra-android-m2repository

jdk:
  - oraclejdk8

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - mksdcard -l e 756M sdcard.img
  - emulator -avd test -no-skin -no-audio -no-window -sdcard sdcard.img &
  - android-wait-for-emulator

script:
  - ./gradlew Snooper:clean Snooper:testDebugUnitTest Snooper:connectedDebugAndroidTest Snooper:lintDebug Snooper:assembleDebug
  - ./gradlew Snooper-Spring:clean Snooper-Spring:testDebugUnitTest Snooper-Spring:connectedDebugAndroidTest Snooper-Spring:lintDebug Snooper-Spring:assembleDebug
