language: android

jdk:
  - oraclejdk8

before_install:
  - echo y | android update sdk --no-ui --all --filter "tools"
  - echo y | android update sdk --no-ui --all --filter "platform-tools"
  - echo y | android update sdk -u -a -t 9,149

script:
  - ./gradlew clean test connectedAndroidTest build --no-daemon
